# Generated by Django 3.1 on 2021-03-14 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_parsingclass'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParsingClass',
        ),
    ]
